// <auto-generated />
using System;
using McpMcp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace McpMcp.Persistence.Migrations.Postgres.Migrations
{
    [DbContext(typeof(McpMcpDbContext))]
    [Migration("20260728151355_SkillMetadata")]
    partial class SkillMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("McpMcp.Persistence.ApiKeyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("McpMcp.Persistence.ApprovalRequestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallerDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CallerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ExpiresAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RedactedArgumentsJson")
                        .HasColumnType("text");

                    b.Property<long>("RequestedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CallerId", "Tool", "Fingerprint", "State");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("McpMcp.Persistence.ApprovalToolRow", b =>
                {
                    b.Property<string>("Tool")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Tool");

                    b.ToTable("ApprovalTools");
                });

            modelBuilder.Entity("McpMcp.Persistence.AssetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PublishedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("References")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequiredTools")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WhenToUse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id", "Version");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("McpMcp.Persistence.AuditEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CallerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CallerRoles")
                        .HasColumnType("text");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<string>("RedactedArgumentsJson")
                        .HasColumnType("text");

                    b.Property<string>("RedactedResponseJson")
                        .HasColumnType("text");

                    b.Property<long?>("RequestBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponseBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Tool")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CallerId");

                    b.HasIndex("ServerId");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Tool");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("McpMcp.Persistence.ConfigVersionRow", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SavedAt")
                        .HasColumnType("bigint");

                    b.HasKey("ServerId", "Version");

                    b.ToTable("ConfigVersions");
                });

            modelBuilder.Entity("McpMcp.Persistence.ConnectorPackageRow", b =>
                {
                    b.Property<string>("PackageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("ActivatedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("GrantedCapabilities")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long>("InstalledAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ManifestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublisherKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Transport")
                        .HasColumnType("integer");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("integer");

                    b.HasKey("PackageId", "Version");

                    b.HasIndex("PackageId", "State");

                    b.ToTable("ConnectorPackages");
                });

            modelBuilder.Entity("McpMcp.Persistence.GuardRuleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("GuardRules");
                });

            modelBuilder.Entity("McpMcp.Persistence.IdentityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("McpMcp.Persistence.ProfileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("LazyToolsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PinnedToolsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("McpMcp.Persistence.PublisherKeyRow", b =>
                {
                    b.Property<string>("KeyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("AddedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("RevokedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("TrustLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.HasKey("KeyId");

                    b.ToTable("PublisherKeys");
                });

            modelBuilder.Entity("McpMcp.Persistence.RedactionRuleRow", b =>
                {
                    b.Property<string>("Tool")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Patterns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Tool");

                    b.ToTable("RedactionRules");
                });

            modelBuilder.Entity("McpMcp.Persistence.RoleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GrantsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("McpMcp.Persistence.TaskRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cancellation")
                        .HasColumnType("integer");

                    b.Property<long?>("ClaimedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpectedInputSchemaJson")
                        .HasColumnType("text");

                    b.Property<long>("ExpiresAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("RedactedInputJson")
                        .HasColumnType("text");

                    b.Property<string>("RedactedResultJson")
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("UpdatedAtTicks")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtTicks");

                    b.HasIndex("State", "ExpiresAtTicks");

                    b.HasIndex("OwnerId", "Tool", "InputFingerprint", "State");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("McpMcp.Persistence.ToolDefinitionPinRow", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tool")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("AcceptedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("AcceptedHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PendingHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("PendingSinceTicks")
                        .HasColumnType("bigint");

                    b.HasKey("ServerId", "Tool");

                    b.ToTable("ToolDefinitionPins");
                });

            modelBuilder.Entity("McpMcp.Persistence.ToolDescriptionOverrideRow", b =>
                {
                    b.Property<string>("Tool")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Tool");

                    b.ToTable("ToolDescriptionOverrides");
                });

            modelBuilder.Entity("McpMcp.Persistence.UiUserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UiUsers");
                });

            modelBuilder.Entity("McpMcp.Persistence.UpstreamOAuthTokenRow", b =>
                {
                    b.Property<Guid>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ExpiresAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("ObtainedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ServerId");

                    b.ToTable("UpstreamOAuthTokens");
                });

            modelBuilder.Entity("McpMcp.Persistence.WebhookRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CallerId")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Webhooks");
                });
#pragma warning restore 612, 618
        }
    }
}
